on:
  push:
    branches:
      - develop
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build --ws --if-present
      - name: Build landing
        run: npm run build-web -w sandbox
      - name: Install wrangler
        run: npm i wrangler
      - name: Idempotent project create
        run: npx wrangler pages project create graphql-editor-dev
        continue-on-error: true
      - name: Publish output
        run: npx wrangler pages deploy ./packages/sandbox/out --branch develop --project-name graphql-editor-dev
